### ISSUE TITLE
LayoutAnimation support for web

### ISSUE THREAD

**Issue by souporserious** [animatedjs/animated#72]
As I was reading through Animated docs I came across LayoutAnimation. Is there any way to support this on the web? I'd love to try and take a stab at this if it's something that you are looking to support. I'm always interested in doing layout animations, specifically auto height animations. I think we can use a [Resize Observer](https://github.com/que-etc/resize-observer-polyfill) to obtain proper dimensions to animate to. Maybe we can create another util that could handle keeping dimensions of a stack of views? I know the hard part is we need to essentially render the content, measure, then animate to that measurement.

I'm curious if you have any ideas for this? I've done previous work with what I call a [fluid container](https://github.com/souporserious/react-fluid-container), but maybe there are other benefits by copying the same API over to web? Thought I'd post to see what you think :) would love to hear your thoughts on this.

**Comment by browniefed** [comment]
I think the reason why LayoutAnimation works is because React Native 1) controls layout 2) has a cache on the native side.

LayoutAnimation is basically a way to register an animation to occur on the next re-render from a `setState`. There are issues with this in that you can't scope it to a particular child element, it just effects everything globally. Also it's just not flexible if you want to build out complex animations.

In the web if you were to register an animation to occur the layout would already take effect before you could control the animation. I just don't think the `LayoutAnimation` paradigm works for the web. Happy to be told I'm wrong though.

**Comment by souporserious** [comment]
Interesting. I might take stab at something along these lines, but it sounds like it should be seperate from here. Thanks for explaining :)
